CREATE TABLE "HR"."I_NOTICE" 
   ("SEQ" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"WRITER" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"REGDATE" DATE, 
	"CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
REM INSERTING into HR.I_NOTICE
SET DEFINE OFF;

INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (1,'お知らせ1','管理者','こうしろああしろ1',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (2,'お知らせ2','管理者','こうしろああしろ2',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (3,'お知らせ3','管理者','こうしろああしろ3',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (4,'お知らせ4','管理者','こうしろああしろ4',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (5,'お知らせ5','管理者','こうしろああしろ5',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (6,'お知らせ6','管理者','こうしろああしろ6',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (7,'お知らせ7','管理者','こうしろああしろ7',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (8,'お知らせ8','管理者','こうしろああしろ8',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (9,'お知らせ9','管理者','こうしろああしろ9',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (10,'お知らせ10','管理者','こうしろああしろ10',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (11,'お知らせ11','管理者','こうしろああしろ11',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (12,'お知らせ12','管理者','こうしろああしろ12',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (13,'お知らせ13','管理者','こうしろああしろ13',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (14,'お知らせ14','管理者','こうしろああしろ14',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (15,'お知らせ15','管理者','こうしろああしろ15',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (16,'お知らせ16','管理者','こうしろああしろ16',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (17,'お知らせ17','管理者','こうしろああしろ17',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (18,'お知らせ18','管理者','こうしろああしろ18',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (19,'お知らせ19','管理者','こうしろああしろ19',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (20,'お知らせ20','管理者','こうしろああしろ20',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (21,'お知らせ21','管理者','こうしろああしろ21',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (22,'お知らせ22','管理者','こうしろああしろ22',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (23,'お知らせ23','管理者','こうしろああしろ23',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (24,'お知らせ24','管理者','こうしろああしろ24',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (25,'お知らせ25','管理者','こうしろああしろ25',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (26,'お知らせ26','管理者','こうしろああしろ26',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (27,'お知らせ27','管理者','こうしろああしろ27',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (28,'お知らせ28','管理者','こうしろああしろ28',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (29,'お知らせ29','管理者','こうしろああしろ29',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (30,'お知らせ30','管理者','こうしろああしろ30',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (31,'お知らせ31','管理者','こうしろああしろ31',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (32,'お知らせ32','管理者','こうしろああしろ32',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (33,'お知らせ33','管理者','こうしろああしろ33',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (34,'お知らせ34','管理者','こうしろああしろ34',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (35,'お知らせ35','管理者','こうしろああしろ35',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (36,'お知らせ36','管理者','こうしろああしろ36',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (37,'お知らせ37','管理者','こうしろああしろ37',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (38,'お知らせ38','管理者','こうしろああしろ38',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (39,'お知らせ39','管理者','こうしろああしろ39',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (40,'お知らせ40','管理者','こうしろああしろ40',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (41,'お知らせ41','管理者','こうしろああしろ41',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (42,'お知らせ42','管理者','こうしろああしろ42',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (43,'お知らせ43','管理者','こうしろああしろ43',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (44,'お知らせ44','管理者','こうしろああしろ44',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (45,'お知らせ45','管理者','こうしろああしろ45',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (46,'お知らせ46','管理者','こうしろああしろ46',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (47,'お知らせ47','管理者','こうしろああしろ47',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (48,'お知らせ48','管理者','こうしろああしろ48',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (49,'お知らせ49','管理者','こうしろああしろ49',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (50,'お知らせ50','管理者','こうしろああしろ50',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (51,'お知らせ51','管理者','こうしろああしろ51',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (52,'お知らせ52','管理者','こうしろああしろ52',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (53,'お知らせ53','管理者','こうしろああしろ53',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (54,'お知らせ54','管理者','こうしろああしろ54',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (55,'お知らせ55','管理者','こうしろああしろ55',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (56,'お知らせ56','管理者','こうしろああしろ56',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (57,'お知らせ57','管理者','こうしろああしろ57',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (58,'お知らせ58','管理者','こうしろああしろ58',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (59,'お知らせ59','管理者','こうしろああしろ59',to_date('21/02/24','RR/MM/DD'),0);
INSERT INTO HR.I_NOTICE (SEQ,TITLE,WRITER,CONTENT,REGDATE,CNT) VALUES (60,'お知らせ60','管理者','こうしろああしろ60',to_date('21/02/24','RR/MM/DD'),0);

CREATE UNIQUE INDEX "HR"."SYS_C007016" ON "HR"."I_NOTICE" ("SEQ") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

ALTER TABLE "HR"."I_NOTICE" ADD PRIMARY KEY ("SEQ")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE;