--------------------------------------------------------
--  ������ ������ - �����-2��-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "HR"."RESERVATION" 
   (	"RNUM" NUMBER, 
	"LECTURENUM" NUMBER(*,0), 
	"MID" VARCHAR2(20 BYTE), 
	"ORDERDATE" DATE DEFAULT sysdate, 
	"STARTDATE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.RESERVATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007121
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007121" ON "HR"."RESERVATION" ("RNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "HR"."RESERVATION" ADD PRIMARY KEY ("RNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  ALTER TABLE "HR"."RESERVATION" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "HR"."RESERVATION" MODIFY ("LECTURENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "HR"."RESERVATION" ADD CONSTRAINT "FK_LECTURE" FOREIGN KEY ("LECTURENUM")
	  REFERENCES "HR"."LECTURECLASS" ("LECTURENUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HR"."RESERVATION" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("MID")
	  REFERENCES "HR"."MEMBER" ("MID") ON DELETE CASCADE ENABLE;
