CREATE TABLE "HR"."I_LECTURECLASS" 
   ("LECTURENUM" NUMBER(*,0), 
	"LECTURENAME" VARCHAR2(200 BYTE), 
	"LECTURECONTENT" VARCHAR2(200 BYTE), 
	"LECTURELISTCONTENT" VARCHAR2(200 BYTE), 
	"LECTUREIMAGE" VARCHAR2(200 BYTE), 
	"LECSIMG" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
REM INSERTING into HR.I_LECTURECLASS
SET DEFINE OFF;

INSERT INTO HR.I_LECTURECLASS (lecturenum,lecturename,lecturecontent,lecturelistcontent,lectureimage,lecsimg) VALUES (1,'Java','コンテンツ','ほげほげ','JAVA.jpg',null);
INSERT INTO HR.I_LECTURECLASS (lecturenum,lecturename,lecturecontent,lecturelistcontent,lectureimage,lecsimg) VALUES (2,'JavaScript','コンテンツ','ほげほげ','JS.png',null);
INSERT INTO HR.I_LECTURECLASS (lecturenum,lecturename,lecturecontent,lecturelistcontent,lectureimage,lecsimg) VALUES (3,'Spring','コンテンツ','ほげほげ','SPRING.png',null);

CREATE UNIQUE INDEX "HR"."SYS_C007018" ON "HR"."I_LECTURECLASS" ("LECTURENUM") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

ALTER TABLE "HR"."I_LECTURECLASS" ADD PRIMARY KEY ("LECTURENUM")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE;