CREATE TABLE "HR"."I_LECTUREVIDEO" 
   ("VIDEONUM" NUMBER, 
	"LECTURENUM" NUMBER(*,0), 
	"VIDEOID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
REM INSERTING into HR.I_LECTUREVIDEO
SET DEFINE OFF;

CREATE UNIQUE INDEX "HR"."SYS_C007137" ON "HR"."I_LECTUREVIDEO" ("VIDEONUM") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

ALTER TABLE "HR"."I_LECTUREVIDEO" ADD PRIMARY KEY ("VIDEONUM")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE;

ALTER TABLE "HR"."I_LECTUREVIDEO" ADD CONSTRAINT "FK_I_VIDEO" FOREIGN KEY ("LECTURENUM")
REFERENCES "HR"."I_LECTURECLASS" ("LECTURENUM") ON DELETE CASCADE ENABLE;