--------------------------------------------------------
--  ������ ������ - �����-2��-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LECTURECLASS
--------------------------------------------------------

  CREATE TABLE "HR"."LECTURECLASS" 
   (	"LECTURENUM" NUMBER(*,0), 
	"LECTURENAME" VARCHAR2(200 BYTE), 
	"LECTURECONTENT" VARCHAR2(200 BYTE), 
	"LECTURELISTCONTENT" VARCHAR2(200 BYTE), 
	"LECTUREIMAGE" VARCHAR2(200 BYTE), 
	"LECSIMG" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.LECTURECLASS
SET DEFINE OFF;

Insert into HR.LECTURECLASS (LECTURENUM,LECTURENAME,LECTURECONTENT,LECTURELISTCONTENT,LECTUREIMAGE,LECSIMG) values (41,'자바스크립트를 잡아','어려웡','잡으라고','JAVA 스크립트.png',null);
Insert into HR.LECTURECLASS (LECTURENUM,LECTURENAME,LECTURECONTENT,LECTURELISTCONTENT,LECTUREIMAGE,LECSIMG) values (26,'Java 감잡기','자바 스크립트와는 다릅니다','자바의 기초부터 배워보자','Java_620X0.jpg',null);
Insert into HR.LECTURECLASS (LECTURENUM,LECTURENAME,LECTURECONTENT,LECTURELISTCONTENT,LECTUREIMAGE,LECSIMG) values (28,'바보라도 아는 스프링','222','111','스프링.png',null);
--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007018" ON "HR"."LECTURECLASS" ("LECTURENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LECTURECLASS
--------------------------------------------------------

  ALTER TABLE "HR"."LECTURECLASS" ADD PRIMARY KEY ("LECTURENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
